config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'home#index'
  get 'doc', to:'home#doc'

  get 'call',to:'ticket#call'
  get 'notrespond',to:'ticket#notrespond'
  get 'close',to:'ticket#close'
  get 'vendor',to:'ticket#vendor'


  get 'login',to:'home#login' 
  post 'login',to:'home#appr'

  delete 'logout',to:'home#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



	def check_login
		if session[:pass]
			return true
		else
			return false
		end
	end


	def require_login
		if !check_login
			redirect_to login_path
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

before_action :require_login,except:[:login,:appr,:destroy]


  def index
  end
  
  def doc
  end

  def login
    @er=nil
  end

  def appr
    passcode = params[:login] 
    if passcode == 'balerjob'
      session[:pass]='loveyou'
      redirect_to root_path 
    else
      @er='red border_red'
      render :login
    end
  end


  def destroy
    # render plain:'del call'
    session[:pass]=nil
    redirect_to login_path
  end

end

app/controllers/ticket_controller.rb
class TicketController < ApplicationController

    before_action :require_login

    def call
    end

    def close
    end

    def vendor
    end
    
    def notrespond
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ticket_helper.rb
module TicketHelper
end

app/views/home/doc.erb
<div class="container mt-2 ">
        <div class="tile is-ancestor">
            <div class="tile is-4 is-vertical is-parent">
              <div class="tile is-child box">
                <p class="title">Ticket Closing Mail</p>
                <p class="title">To:</p>
                <li>User's Email</li>
                <p class="title">
                   CC:
                </p>
                <li>KolkataIS.IMLeads@tcs.com</li>
                <hr>
                <p class="title-2">Ticket Closing Mail</p>
              </div>
              
              <!-- <div class="tile is-child box">
                <p class="title">Two</p>
              </div> -->
            </div>
            <div class="tile is-parent">
              <div class="tile is-child box">
                <p class="title">Infospace Vendor approval mails</p>
                <p class="title ">To:</p>
                <li>p.ghosh3@tcs.com</li>
                <li>Balbinder.Chauhan@tcs.com</li>
                <li>infospacekol.security@tcs.com</li>
                <li>infospacebpokol.adminhelpdesk@tcs.com</li>
                <li>Nirmalya.kar@tcs.com</li>
                <li>security.candorkol@ap.jll.com</li>
                <p class="title"></p>
                <p class="title">Oval Vendor approval mails</p>
                <p class="title">To:</p>
                <li>security.candorkol@ap.jll.com</li>
                <li>munmun.guha@tcs.com</li>
                <li>ovalkol.security@tcs.com</li>


              </div>
            </div>
          </div>
    </div>

app/views/home/index.html.erb
    <div id="chage_content ">
      <section class="hero is-medium is-link is-fullheight is-dark" >
        <div class="container hero-body has-text-centered is-dark">
          <div class="">
            <p class="title">
             Email Generator
            </p>
            <p class="subtitle">
              for alsis
            </p>
          </div>
        </div>
      </section>
    </div>

app/views/home/login.html.erb
<div class="login_container">
  <div class="loginbox <%= @er %>">
    <%= form_with url:login_path,class:'login_form' do |f| %>
      <h1 class="fd"><i class="fa-sharp fa-solid fa-lock"></i></h1>
      <label class="labelloin <%= @er %>" for='login'>Enter your passcode to access</label>
      <% if @er %>
        <%= f.password_field :login ,placeholder:"Enter passcode",id:'loginpass',class:'x red border_red'%>
        <%= f.submit "For god's sake let me in",id:'loginbtn' ,class:'xbtn red border_red'%>
      <% else %>
        <%= f.password_field :login ,placeholder:"Enter passcode",id:'loginpass',class:'x'%>
        <%= f.submit "For god's sake let me in",id:'loginbtn' ,class:'xbtn'%>
      <% end -%>
    <% end -%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Email Generator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> <%= csp_meta_tag %> <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <!-- bulma css -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css"
    />
    <!-- fontawesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
      integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
  </head>

  <body>
    <% if session[:pass] %>
    <%= render '/partials/nav' %> 
    <% end -%>
    <%= yield %>
    <%= javascript_include_tag 'close.js' %>
    <%= javascript_include_tag 'calllog.js' %>
    <%= javascript_include_tag 'notrespond.js' %>
    <%= javascript_include_tag 'vendor.js' %>
    
  </body>
</html>

app/views/partials/_nav.erb
<nav class="navbar is-info" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
          <%= link_to root_path,class:'navbar-item' do %>
            <h1 class='title is-1 is-white'> <i class="fa-solid fa-envelope"></i> EmpT</h1>
          <% end %>


    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      


     
      <%= link_to 'Documentaion',doc_path,class:'navbar-item' %>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          

          <%= link_to 'Ticket closing mail',close_path,class:'navbar-item'%>
          <%= link_to 'Ticket closing mail call log',call_path,class:'navbar-item'%>
          <%= link_to 'Not respoding',notrespond_path,class:'navbar-item'%>
          <%= link_to 'Vendor mail',vendor_path,class:'navbar-item'%>
          
          <hr class="navbar-divider">
          
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
        
          <%= button_to 'Get Out',logout_path,class:'button is-danger' ,method: :delete%>
          
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/ticket/call.erb
<div class="container mt-5 box">
  <h1 class="title">Call Log</h1>
  <div class="field">
    <label class="label">Ticket Number</label>
    <div class="control">
      <input
        class="input"
        type="text"
        placeholder="Enter Ticket Number"
        id="tcall_tnumber"/>
    </div>
  </div>

  <div class="field">
    <label class="label">User's Name</label>
    <div class="control">
      <input
        class="input"
        type="text"
        placeholder="Enter User's Name"
        id="tcall_uname"/>
    </div>
  </div>

  <label class="label">Vendor</label>
  <div class="select">
    <select id="vendor_list">
      <option value="HP">HP</option>
      <option class="Acer">Acer</option>
      <option class="Lenovo">Lenovo</option>
      <option value="DELL">DELL</option>
    </select>
  </div>
  <label class="label">Case id</label>
  <input
    class="input"
    type="text"
    placeholder="Enter case id"
    id="tcall_caseid"/>

  <div class="field mt-5">
    <button class="button is-success" onclick="tick_call_fun()">Generate</button>
  </div>

  <div class="field" >
    <label for="" class="label">Email Sub</label>
    <div class="field is-grouped">
    <input type="text" placeholder='Email Sub' readonly='true' id="tcall_sub"  class="input">
    <button class="ml-2 button is-success is-light" onclick="copy_tick_call_close_sub()">Copy Sub</button>
    </div>

  </div>
  <div class="field">
    <label  class="label">Email Body</label>
    <textarea name="tc_msg" id="tcall_msg" class="textarea is-large" readonly="true"></textarea>
    <button class="button is-success is-light mt-2" onclick="copy_tick_call_close_body()">Copy Body</button>



  </div>
</div>

app/views/ticket/close.html.erb
<div id="chage_content">
  <div class="container mt-5 box">
  <h1 class="title">Ticket closing</h1>
    <div class="field">
      <label class="label">Ticket Number</label>
      <div class="control">
        <input
          class="input"
          type="text"
          placeholder="Enter Ticket Number"
          id="tc_tick_number"
        />
      </div>
    </div>
    <div class="field">
      <label class="label">User's Name</label>
      <div class="control">
        <input
          class="input"
          type="text"
          placeholder="Enter User's Name"
          id="tc_uname"
        />
      </div>
    </div>
    <div class="field">
      <button class="button is-success is-light" onclick="closeFunc()">
        Generate
      </button>
    </div>
    <div class="field" id="tc_sub">
      <label   class="label">Email Sub</label>
      <div class="field is-grouped">

        <input
        class="input"
        type="text"
        placeholder="email sub"
        id="tc_email_sub"
        readonly="'true"/>
        
        <button class="button is-success is-light ml-2" onclick="copy_ticket_closing_sub()">Copy Sub</button>

      </div>
    </div>
    <div class="field" id="tc_msg">
     <label class="label">Email Subject</label>
        <textarea name="tc_msg" id="tc_msg_field" class="textarea is-large" readonly="true"></textarea>
        <button class="button is-success is-light mt-2" onclick="copy_ticket_closing_body()">Copy Body</button>

    </div>
  </div>
</div>

app/views/ticket/notrespond.erb
<div id="chage_content">

  <div class="container mt-5 box">
  <h1 class="title">Not responding</h1>
    <div class="field">
      <label class="label">Ticket Number</label>
      <div class="control">
        <input
          class="input"
          type="text"
          placeholder="Enter Ticket Number"
          id="notrespond_tick_number"
        />
      </div>
    </div>
    <div class="field">
      <label class="label">User's Name</label>
      <div class="control">
        <input
          class="input"
          type="text"
          placeholder="Enter User's Name"
          id="notrespond_tc_uname"
        />
      </div>
    </div>
    <div class="field">
      <button class="button is-success is-light" onclick="gen_notrespond()">
        Generate
      </button>
    </div>
    <div class="field" id="tc_sub">
      <label   class="label">Email Sub</label>
      <div class="field is-grouped">

        <input
        class="input"
        type="text"
        placeholder="email sub"
        id="notrespond_tc_email_sub"
        readonly="'true"/>
        
        <button class="button is-success is-light ml-2" onclick="notrespond_sub_copy()">Copy Sub</button>

      </div>
    </div>
    <div class="field" id="tc_msg">
     <label class="label">Email Sub</label>
        <textarea name="tc_msg" id="notrespond_tc_msg_field" class="textarea is-large" readonly="true"></textarea>
        <button class="button is-success is-light mt-2" onclick="notrespond_body_copy()">Copy Body</button>

    </div>
  </div>
</div>

app/views/ticket/vendor.erb
<!-- <h1 class="title container mt-5 is-dark" align="center">Vendor Mail</h1> -->
<div class="container mt-5 box">
  <h1 class="title">Vendor</h1>

  <div class="field">
    <label class="label">Vendor Name</label>
    <div class="control">
      <input
        class="input"
        type="text"
        placeholder="Vendor name"
        id="vendor_name"
      />
    </div>
  </div>
  <div class="field">
    <label class="label">Vendor Company</label>
     <div class="field select">
    <select id="vechicle_comp">
      <option value="DELL">DELL</option>
      <option value="Lenovo">Lenovo</option>
      <option value="Acer">Acer</option>
      <option value="HP">HP</option>
    </select>
  </div>
  <div class="field">
    <label class="label">Vendor has vehicle?</label>
  </div>

  <div class="field select">
    <select id="vechicle_drop">
      <option value="N">No</option>
      <option value="Y">Yes</option>
    </select>
  </div>

  <label class="label">ODC</label>
  <div class="select">
    <select id="odc">
      <option value="Infospace AI 7 ODC C IS Room">Infospace 7 ODC IS Room</option>
      <option value="Oval GIII 6 ODC IS Room">Oval GIII 6 ODC IS Room</option>
      <option value="Sabina Park BII 2 ODC IS Room">Sabina Park BII 2 ODC IS Room</option>
    </select>
  </div>

  <div class="field mt-5">
    <button class="button is-success" onclick="vendor_gen()">Generate</button>
  </div>

<div class="box">
  <div class="field" id="vendor_sub">
  	<label class="label">Email Sub</label>
  	<div class="field is-grouped">
  		<input type="text" id="vendor_email_sub" placeholder="Email Sub" readonly='true' class='input'/>
  		<button class="button is-primary ml-2" onclick="vendor_sub_copy()">Copy Sub</button>
  	</div>
  </div>
  <div class="field" id="vendor_body">
  		<div class="field">
  			<label class="label">Email Body</label>
  			<textarea class="textarea is-large" id="vendor_email_body"  readonly='true' placeholder="Email body"></textarea>
  		<button class="button is-primary mt-2" onclick="vendor_body_copy()">Copy Body</button>
  		</div>
  </div>
  </div>
</div>